### ISSUE TITLE
Mongotail EXCEPTION - Unknown registry

### ISSUE THREAD

**Issue by mangel1196** [mrsarm/mongotail#26] opened 2018-01-22 21:12 UTC
when i execute mongotail <dbname> - f show this:

Mongotail EXCEPTION - Unknown registry
Dump: {"ns": "usersSantander.usersSantander", "command": {"filter": {"username": "uid1"}, "$db": "usersSantander", "lsid": {"id": UUID("f9b97a39-221c-45dc-9532-e3165186c53b")}, "find": "usersSantander"}, "ts": ISODate("2018-01-22T20:43:06.721Z"), "nreturned": 1, "op": "query"}
Mongotail EXCEPTION - Unknown registry
Dump: {"ns": "usersSantander.usersSantander", "command": {"filter": {"username": "uid2"}, "$db": "usersSantander", "lsid": {"id": UUID("f9b97a39-221c-45dc-9532-e3165186c53b")}, "find": "usersSantander"}, "ts": ISODate("2018-01-22T20:56:20.817Z"), "nreturned": 1, "op": "query"}
Mongotail EXCEPTION - Unknown registry
Dump: {"ns": "usersSantander.usersSantander", "command": {"filter": {"username": "uid3"}, "$db": "usersSantander", "lsid": {"id": UUID("f9b97a39-221c-45dc-9532-e3165186c53b")}, "find": "usersSantander"}, "ts": ISODate("2018-01-22T21:01:32.228Z"), "nreturned": 1, "op": "query"}
Mongotail EXCEPTION - Unknown registry
Dump: {"ns": "usersSantander.usersSantander", "command": {"filter": {"username": "uid4"}, "$db": "usersSantander", "lsid": {"id": UUID("f9b97a39-221c-45dc-9532-e3165186c53b")}, "find": "usersSantander"}, "ts": ISODate("2018-01-22T21:02:57.218Z"), "nreturned": 0, "op": "query"}

in centos 7

**Comment by mrsarm** [comment] 2018-01-22 22:14
@mangel1196 Are you using MongoDB 3.6? I saw errors like these with the new database version, looks like the MongoDB team changed again the way the logs are persisted in the profiling system. I have to add a new `if mongo_version > "3.6": ...get the info in another way...`.

**Comment by ankit1329** [comment] 2018-02-05 08:36
@mrsarm I get this error when i duplicate a collection using robomongo.
MongoDB version 3.4.9

**Comment by mrsarm** [comment] 2018-02-05 13:39
@ankit1329 ok, i'll check, but that looks like another issue. What version of Robomongo you have?

**Comment by ankit1329** [comment] 2018-02-06 05:16
@mrsarm  robomongo version 3.2.0-34-g9fa2d97
Tried this in latest version of robo3T --version _v3.4.3-8-g05b19c6_. Same Unknown Registry exception.

**Comment by mrsarm** [comment] 2018-02-10 18:46
@ankit1329 I tested to see what happens duplicating a collection but with latest Robo 3T version (formerly Robomongo) and logs are displayed without errors with latest mongotail, try use the latest Robo 3T, you souldn't use old versions of Robomongo because they have a poor support of new features present in MongoDB 3.0+

@mangel1196 I'll try to fix the issue with Mongo 3.6 today

**Comment by mrsarm** [comment] 2018-02-10 19:02
@ankit1329 wait! I could reproduce the error also with latest Robo 3T version, fixing ...

**Comment by mrsarm** [comment] 2018-02-10 22:53
Fixed both issues in master branch, going to be released in v2.2.0

**Closed as completed** 2018-02-11 04:43 UTC
Labels: bug

**Comment by ankit1329** [comment] 2018-02-12 05:16
@mrsarm  thanks a lot.. :)
